# Generated by Django 4.1.3 on 2025-06-13 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_alter_fileupload_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_knoxauthtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatido',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='whatido',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_about_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_about_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_user_about', to='commons.fileupload'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_about_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='what_i_do_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserAbout',
        ),
        migrations.DeleteModel(
            name='WhatIDo',
        ),
    ]
